name: Cek Kode HTML (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # Menyesuaikan versi Node.js

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Periksa HTML
        run: htmlhint "/*.html"
